global:
  scrape_interval: 15s # Mặc định lấy dữ liệu mỗi 15 giây

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "fastapi-app"

    # Tần suất Prometheus đi lấy dữ liệu (mặc định 15s)
    scrape_interval: 5s

    static_configs:
      # Địa chỉ của Container FastAPI
      # Lưu ý: 'fastapi' là tên service trong docker-compose, '80' là cổng nội bộ
      - targets: ["fastapi:80"]
